### ISSUE TITLE
Location translations are misbehaving

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1060]
Something is wrong with the locations displaying in sandbox - some locs are displaying the wrong text - maybe because they are CURRENT_HOME_LOCS?

https://sw-webapp-sandbox-b.stanford.edu/view/3402192
current loc CHEM-RESV - treated as home loc
translation is 
'CHEM-RESV' => 'On reserve at Swain Library',
appears as "Ask at circulation desk"
![screen shot 2015-10-01 at 12 31 40 pm](https://cloud.githubusercontent.com/assets/6945691/10231572/66321d5e-6838-11e5-9cba-fdfa5d06f2bb.png)

https://sw-webapp-sandbox-b.stanford.edu/view/6990605
in sandbox, this record has k| SEE-LOAN l| INPROCESS
in prod, it has k| INTRANSIT l| INPROCESS
when we looked at this record on Tuesday, sandbox matched prod, but the display was the same.
![screen shot 2015-10-01 at 12 35 27 pm](https://cloud.githubusercontent.com/assets/6945691/10231689/03a666bc-6839-11e5-9b0d-9f7f8595f3fa.png)

(Note that SEE-LOAN is on the HIDE_DUE_DATE_CURRENT_LOCS list and that doesn't seem to be working - but that's not related to requests.)

In addition to figuring out why CHEM-RESV is displaying incorrectly... please make the following changes to the constants:

* [x] REMOVE SEE_LOAN from CURRENT_HOME_LOCS - so these items will be grouped under their home loc and will be interfiled with other items at that loc.

* [x] ADD:
```
           'MM-ARTCAB' => 'Microfiche collection B',
           'MM-BUSCAB' => 'Microfiche collection A',
           'MM-DIZOCAB' => 'Microfiche collection D',
           'MM-MATHCAB' => 'Microfiche collection C',
           'MM-CDCAB' => 'Ask at Media Microtext desk',
           'MM-CMPACT2' => 'Ask at Media Microtext desk',
           'MM-OVERSIZ' => 'Ask at Media Microtext desk',
           'MM-STACKS' => 'Ask at Media Microtext desk',

           'RAUB-NUM' => 'Frank L. Kovacs Numismatic Library',
```

* [x] CHANGE:
```
           'SHELBYTITL' => 'Serials',
           'RAUB-COLL' => 'Raubitschek Collection of Papyrology and Epigraphy',
           'PAGE-LN' => 'Paged to Medical Library',
```

**Comment by jkeck** [comment]
@jvine wrt the first issue, the reason is a bit strange now that I track it down (keep in mind this is all code that was ported from the old availability code).

We are treating that current location as a home location as well as proxying it through a [different location code](https://github.com/sul-dlss/SearchWorks/blob/requests-dev/lib/constants.rb#L578) `SW-RESERVE-DESK`.  This is because the current location is one of the [configured reserve desks](https://github.com/sul-dlss/SearchWorks/blob/requests-dev/lib/constants.rb#L901-L917) so we proxy the location code to be `SW-RESERVE-DESK` instead of `CHEM-RESV` and it is treated like a home location.

So I'm not entirely sure what we should do here.  I have the rest of the issues ready to go.

**Comment by jvine** [comment]
Short term fix: change this translation for now...

'SW-RESERVE-DESK' => 'On reserve:  Ask at circulation desk',

... and we can look at whether it would be better to remove the proxy in SW3.1 work.

**Comment by jvine** [comment]
Done w Requests
