### ISSUE TITLE
Linking behaviour for 76x - 78x serials

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1121]
Currently: If 785 $t is present we do search_title; if $x we do all fields.

Desired behaviour, for all fields in the 76x - 78x range:
- [ ] If $s or $t is present (but not $a), do search_title 
- [ ] If $s AND $t are present, choose $s
- [ ] If $a is present - plus $s or $t - combine to search author_title
- [ ] If $x (ISSN) or $z (ISBN) is present, link it (separately) to isbn_search

Example with $a and $s
https://searchworks.stanford.edu/view/10750756

Example with linked $t that also has $a - only $t currently linked
https://searchworks.stanford.edu/view/10781763

Example with ISSN - currently doing all-fields search
https://searchworks.stanford.edu/view/358080

SW-1496, SW-494, SW-681, INDEX-217

**Comment by jkeck** [comment]
Should the search_title and/or the search_author be quoted searches (or any part of it)?

In the current implementation $t is quoted but also linked by itself since it is not currently combined with $a.

(FYI, the examples 10750756 and 10781763 will both only return themselves as a result with a quoted search).

**Comment by jvine** [comment]
Confirmed with Kay: They should be quoted searches.
