### ISSUE TITLE
SAL3 item shows as available when it is checked out or on hold

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1179]
SW-1580, but any examples are ephemeral.

Part 1: SAL3 item is paged to Green for user A. User B sees item with current loc of "Ask at circulation desk" and green truck (Available). Item is at circ desk but is on hold for user A - i.e. not available. Not sure if this is something we used to handle but lost along the way.

Part 2: User A checks out the book that was on hold. Now it is checked out and live lookup returns a due date, but the item still shows green truck (Available). 

So are we just not ever overriding the initial status for SAL3?

![screen shot 2016-02-03 at 2 00 55 pm](https://cloud.githubusercontent.com/assets/6945691/12798512/afb02aea-ca7e-11e5-90bd-83f231b30d48.png)

possibly related to #1048 and #1117

**Comment by jkeck** [comment]
We are no longer overriding the status for anything that is known up-front I'm afraid.  I think we may need to just make exceptions to that rule because there are cases where we really do not want to update the status (like an item that is known to have a red-X but looks like is on the shelf from a live-lookup).
