### ISSUE TITLE
Date slider bug - shows count only to the first comma.

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1301]
SW-1778

**Comment by jkeck** [comment]
The first released version of `blacklight_range_limit` with the fix for the comma issue unfortunately relies on functionality added in Blacklight 5.10 (which we are on 5.8.2).  We'll need to upgrade to at least the latest 5.10 release in order to upgrade to a version of `blacklight_range_limit` with this fix.  I've done that locally and along with the many expected deprecation warning, we have a few failing tests.  I'll try to look at them when I have time.

**Comment by drh-stanford** [comment]
@jkeck this seems blocked by the Blacklight upgrade, correct?

**Comment by jkeck** [comment]
@drh-stanford  it looks like this was addressed projectblacklight/blacklight_range_limit#36 which appears to be in the 5.x line of Blacklight.  If we can try to update to the latest version possible (or the latest version that has that fix in it) then we should be good to go.

**Comment by jkeck** [comment]
Ah, it looks like that fix wasn't released until BlacklightRangeLimit 5.1.0, which does require a different version of Blacklight (although the gemspec doesn't correctly identify that, so it is possible to install it while it will not work.

**Comment by jkeck** [comment]
We've updated the range limit dependency which addresses this issue.

The underlying problem was that the commas being interpreted as decimal points by one of the libraries involved in the range limit plugin.  This was addressed by removing the commas all-together.
