### ISSUE TITLE
Add StackMap to Art

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#1304]
Waiting to hear back if they have any location exclusions.

**Comment by saseestone** [comment]
Got an answer for Vanessa Kam in Art.  They have a long list of Home Location **exclusions:**
ARTLCKL
ARTLCKL-R
ARTLCKM
ARTLCKM-R
ARTLCKO
ARTLCKO-R
ARTLCKS
ARTLCKS-R
MEDIA
MEDIA-FOLI
MICROFILM
MICROTEXT

Jessie indicated that he wanted a list of "physically accessible" locations that shouldn't have links.  I didn't know if he'd interpret the Locked Stacks locations as accessible or not.  I suppose not.  so that would cut the list down to:

MEDIA
MEDIA-FOLI
MICROFILM
MICROTEXT

Sarah

**Comment by jkeck** [comment]
Acceptance criteria
* Items in library ART should get a stackmap link for home locations that are **not** in the list above. (the larger list of locations).
* This location list should only apply to ART (e.g. other Stackmap libraries should not use this list).
* Not to be too prescriptive, but it might be nice to have a default list (the current stackmap locations) that are applied, and libraries (like ART) can opt-in to provide their own blacklists.

**Comment by drh-stanford** [comment]
@jkeck do you have an example of an item that has a stackmap in the ART library? My code changes enable the ART - STACKS location to be stackmapable, but the URL I'm seeing for 12062765 isn't showing a map:

https://searchworks.stanford.edu/view/12062765/stackmap?callnumber=NB621+.M6+A13+2017&library=ART&location=STACKS&title=100+anni+%3A+scultura+a+Milano%2C+1815-1915
