### ISSUE TITLE
Prevent auto-complete for Request forms

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#1318]
Browser changes in auto-fill have started causing issues ie phone numbers in the id field. 

[SW-1794](https://jirasul.stanford.edu/jira/browse/SW-1794)

**Comment by drh-stanford** [comment]
@jkeck it looks like we can add `autocomplete="off"` to the `form` element, but isn't this a change in the sul-requests codebase? In particular, here -- https://github.com/sul-dlss/sul-requests/blob/9ab317e2ecf2108c27447d24b21f4f07a9e28846/app/helpers/application_helper.rb#L7-L17

**Comment by jkeck** [comment]
@drh-stanford yes, this change would be in the SUL-Requests codebase (not SearchWorks, but the two projects are tightly connected, which is why we're dealing w/ this work in this cycle).

And appolgies that this doesn't have very good acceptance criteria on this ticket.

I think we want to just add `autocomplete="off"` to particular form fields.  I don't think we would want it on the entire form element as we would like to allow people to autocomplete their email address/name, etc. I know library_id is the main field that is cuasing problems here.  @jvine can you think of any others that we should do while we are in there?

**Comment by jvine** [comment]
There's no hidden honey-trap field in this form, right? That's the only other thing I think is affected.

**Comment by jkeck** [comment]
@jvine I don't believe there is, no, but we can double check.  I think that was primarily in the feedback form.
