### ISSUE TITLE
Change label "language" to "notation" for music

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#1319]
Leader/06 = c or d 
and 
546 contains only subfield |b 
the Searchworks display label for the field should be Notation. 

(It would also be cool to get rid of the ". " that precedes the subfield 
|b data when there is no subfield |a present)

[SW-1077](https://jirasul.stanford.edu/jira/browse/SW-1077)
 
Examples
http://searchworks.stanford.edu/view/10093706 
http://searchworks.stanford.edu/view/9217198 
http://searchworks.stanford.edu/view/10108264

**Comment by jvine** [comment]
Per Jessie, we don't have access to the leader here, but can use something we're already indexing, such as resource type.

Resource type = "Music score" will get 99% of the relevant items.

Example that would not be captured:  https://searchworks.stanford.edu/view/9645653 

Do we know in the record view if an item has more than one resource type assigned? (In the future there will be quite a few that have "Music score" AND "Archive/Manuscript". https://searchworks.stanford.edu/?f%5Bformat_main_ssim%5D%5B%5D=Archive%2FManuscript&f%5Bformat_main_ssim%5D%5B%5D=Music+score)

Example record that should not get the "Notation" label because there's also a subfield a.
https://searchworks.stanford.edu/view/11412204
