### ISSUE TITLE
Add pagination to search results

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1391]
- default to 20 results per page (can be changed by the user)
- if there are more than the "per page" results returned, show pagination at the bottom; if less, no pagination
- current page is highlighted
- on first page, "previous" is disabled

<img width="412" alt="screen shot 2017-06-23 at 10 54 12 am" src="https://user-images.githubusercontent.com/6945691/27494382-8351ab64-5802-11e7-8e0c-0edb056f9570.png">

**Comment by drh-stanford** [comment]
It looks like EDS restricts our maximum number of results to 250.

```
{"DetailedErrorDescription"=>"Requested records starting at # 261. Max start request number is : 251 ", "ErrorDescription"=>"Max Record Retrieval Exceeded", "ErrorNumber"=>"138"}
```

Is this configurable via the Admin UI, or is it a hard limit?

**Comment by drh-stanford** [comment]
Bill says this (250 max results) is a hard limit in the EDS API.

**Comment by drh-stanford** [comment]
Turns out the hard limit is the number of results between page requests. Specifically:

> "In order to optimize system performance, we have introduced a limit on the number or records that can be skipped over when iterating over a result set. The maximum number of records that can be jumped over is returned in the info response message as the 'MaxRecordJumpAhead' in the 'ApiSettings' section.
As an example: with a max record jump ahead of 250, if the last request was for page = 1 and results per page = 10 (i.e. records 1-10 were requested), the max page number that can be requested is 27 (i.e. records 261-270, skipping records 11-260). If the results requested are beyond the max jump ahead number, error code: 138 - "Max Record Retrieval Exceeded" will be returned."

The implications of this is that the UI of letting the user select a page (e.g., going from page 3 to 7 with results per page set to 100) will throw an error at the EDS API level.

**Comment by drh-stanford** [comment]
I changed the criteria as follows:

- Only Previous/Next UI for the top and bottom (due to EDS API constraint on page skipping)

Here's what the paging looks like right now in my branch:

### Typical case

#### Header
![screen shot 2017-06-26 at 2 05 29 pm](https://user-images.githubusercontent.com/1861171/27560649-d721fb1c-5a79-11e7-9d05-389ff1e4429b.png)
#### Footer
![screen shot 2017-06-26 at 2 05 40 pm](https://user-images.githubusercontent.com/1861171/27560654-dc1519a6-5a79-11e7-862c-682f5286d81a.png)

### Single page results

![screen shot 2017-06-26 at 2 10 02 pm](https://user-images.githubusercontent.com/1861171/27560679-f349af9c-5a79-11e7-81e0-9ba429b1c957.png)

### No results page

![screen shot 2017-06-26 at 2 06 01 pm](https://user-images.githubusercontent.com/1861171/27560694-fff81b98-5a79-11e7-94f9-cd02e81faba0.png)
