### ISSUE TITLE
Source type facet behaviour - turn on the counts again when Ebsco fix is ready

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1508]
Start with * search -> 423,729,594 results

1. Source type > Academic Journals shows count of 207,037,882
   - Click it, get 273,678,904 results
      - expected 207,037,882
   - Academic Journals[x] facet value now shows count of 273,542,336
      - expected to match total results
2. Source type > Reviews has 4,399,511
   - Click it, get 291,143,544 results
      - expected 4,399,511
   - Reviews[x] has 21,864,151
      - expected to match total results (or even previous count, but not something totally new?!)
3. Language > english has 234,536,271
   - Click it, get 232,843,203 results
      - expected 234,536,271
   - and now english is removed from language facet
      - expected english[x] 234,536,271 in lang facet
4. Topic > book reviews has 1,033,508
   - Click it, get 1,033,536 results  <- close, maybe legit?
      - expected 1,033,508 results 
   - value removed from topic facet
      - expected book reviews[x] 1,033,508 in topic facet
5. Topic > general shows count of 5,008
   - Click it, get 5,008 results - good!
   - Topic facet is gone altogether
      - expected the facet to appear with 2 values: 
         - book reviews[x]  5,008
         - general[x]  5,008

**Comment by jkeck** [comment]
@jvine just taking a look at this before I try to rope in the EBSCO folks.

What happens if you're not doing a `*` search?  (e.g. some search term) Are the number differences a bit closer to what you might expect?  I'm noticing that the asterisk is getting URL encoded at some point, and am wondering if that has something to do w/ it.

**Comment by jvine** [comment]
- "solar cars"  -> 726,828 results
- Academic journals 275,012
   - apply facet -> 275,812 results
   - Academic journals [remove] 275,011
- Reviews 1,685
   - apply facet -> 281,557 results
   - Reviews [remove]	7,430
- Language - english 271,684
   - apply facet -> 271,409 results
   - english removed from Language facet
- Topic - science 10,355
   - apply facet -> 10,356 results
   - science removed from Topic facet
- etc.

Value remains in facet with [remove] (correct behaviour) for 
- options
- source type
- database

Value is removed from facet, and facet is removed altogether when there are no more unselected values, for:
- language
- topic
- geography
- Journal title
- publisher

Values within a facet seem to be OR for 
- source type

AND for
- language
- topic
- geography
- journal title, publisher, database (I think these have only one value per result)

Occasionally I get a combination of Topics that gives 0 results, even though the facet values show that there should be results - but I can't reproduce.

**Comment by jvine** [comment]
I did a very specific search:
https://sw-webapp-sandbox-f.stanford.edu/article?q=Aidan+Hehir%2C+%E2%80%9CAssessing+the+influence+of+the+Responsibility+to+Protect+on+the+UN+Security+Council+during+the+Arab+Spring%2C%E2%80%9D&search_field=search

Gets 2 results. 

**Issue 1:  Source type - Academic journals = 5** 

Any facet value should not have a count higher than the actual number of results) - is it totaling up the values in the Databases (Content provider) facet? 

![screen shot 2017-08-01 at 4 49 56 pm](https://user-images.githubusercontent.com/6945691/28851777-c763d282-76d9-11e7-8dd4-20b6a9989135.png)

**Issue 2:  The other facets are all missing.** 

Compare a 2-item result in SearchWorks catalog: https://searchworks.stanford.edu/?q=Ogonek+%3A+dodatek+do+Kolejki&search_field=search
All facets are shown with the values that apply to the search result.

**Comment by efrierson** [comment]
Expected behavior for last comment in this thread.  The results list itself has been de-duplicated, leaving only 2 unique results, whereas the facet values are reflecting pre-de-duplicated counts.  If you click through the Database options, you'll see we get a record for _Assessing the influence of the Responsibility to Protect on the UN Security Council during the Arab Spring_ from four of our content providers, and this has been de-duped in the results list to only 1 result item.  There is a different article that also matches the search in COMPLIMENTARY index, and it is the second results.  

In total, 5 records (all Academic Journals) were found for this search, and 3 we de-duped out of the results list.  

The way we handle this in the native UI is to display a message when exact matches have been de-duplicated; I don't think we include this notification in the API, so I could turn that into an Enhancement Request with the API if it seems like something you'd want included.  I think having the facet counts reflect de-duplication will be a bit more of an architectural challenge.

As for the disappearance of the other facets, the Source Type and Database facets are unique in that they will always appear.  The rest will only appear for searches with greater than 5 or 6 results, but I'll confirm this.  [This search](https://sw-webapp-sandbox-f.stanford.edu/article?utf8=✓&search_field=search&q="UN+Security+Council+during+the+Arab+Spring"+OR+"BusyKid+Helping+Kids+Learn+How+to+Thrive"+OR+"+BusyKid+Joins+Forces+with+Stockpile"+OR+"Arkansas+officials+not+ready"), for example, shows all the facets, but you get any more narrow and they disappear (the assumption being you can just browse the results at this point).

@jvine - Those numbers seem expected too.  The SOURCE TYPE facet ORs together when you select multiple facets, always.  The DATABASE facet will always limit you down to just that DATABASE [I opened an enhancement request a few weeks ago about this - because the Native UI still shows the available databases, whereas the API does not - I will check in on this one].  The REST can be OR'd or AND'd.  ANDing is the right route to go for a set up like this where users click on one at a time to narrow their results.  You could implement a checkbox system that would allow you to select multiple facet values at the same time; these could be OR'd if you did that.

I do have my own install of the article-search branch and I keep it up to date, so the links you provide in these issues are good enough for us to duplicate the issue in our local version.

**Comment by jvine** [comment]
@efrierson The issue is that the facet behaviour as it exists doesn't match the standard Blacklight behaviour - so we'll have a different experience in the catalog vs. article search, and it will be difficult for our users to predict what will happen, depending which part of SearchWorks they learn first. 

I'm most concerned about:
1. the selected values that are removed from the facet, instead of being listed at the top of the facet with a "remove" option. Is this something that can be changed, on your side or ours?
2. facet counts that dramatically _increase_ after the value is selected. I see there are 1,685 Reviews in my result set; I select that facet; and now there are 7,430 Reviews. That seems really counter-intuitive to me, even allowing for ANDing source types. Can you explain, pls?

**Comment by jvine** [comment]
Will be completed by #1650
