### ISSUE TITLE
Specific search throws an error: meme evolution

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1516]
I can search for **meme**, and I can search for **evolution**, but **meme evolution** gives: 
![screen shot 2017-07-24 at 5 29 08 pm](https://user-images.githubusercontent.com/6945691/28550433-9e0c5642-7095-11e7-8903-f475c016a594.png)

Other 2-word searches work, including searches with **meme** and **evolution** in them.

:rofl:

**Comment by jkeck** [comment]
I believe this is caused by a particular record being returned in that result set.

The ID of one of the objects returned is `edsarl__edsarl_10031243_201008_201009280030_201009280030_58_62+69` (notice the `+`).

A `+` signifies a space in a URL, and that's why this is getting confused.  We can allow `+` for the article controller's ID parameter if we should expect that this `+` is a legitimate part of the identifier.

**Comment by drh-stanford** [comment]
@bmckinney is there documentation on the allowable characters in accession identifiers?
