### ISSUE TITLE
Display MODS alternative title

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#1634]
Alternative title from MODS record doesn't display. 
https://searchworks.stanford.edu/view/ky910zy0024 
Additional example - https://searchworks.stanford.edu/view/bq097ny3917

**Please see spec in comment from Arcadia below**

https://jirasul.stanford.edu/jira/browse/SW-1838

**Comment by arcadiafalcone** [comment]
Titles with a type attribute should display with field labels as follows:

- value of displayLabel attribute if present, otherwise:
- if type = "abbreviated", "Abbreviated title"
- if type = "translated", "Translated title"
- if type = "alternative", "Alternate title"
- if type = "uniform", "Uniform title"

These are the only values for title type that are valid MODS.
