### ISSUE TITLE
Empty search gives "We're sorry..." message

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#1752]
User report - enter nothing in the search bar, click the search button, get error message.

**Comment by drh-stanford** [comment]
@jvine What should be the expected behavior? That is, should we show a different error message or No results or what? EDS is failing in this case as you cannot search with an empty query. 

I think this error would happen if they delete the components in their breadcrumbs too, but it shows them a No results page:

### Search for kittens
![screen shot 2017-09-11 at 4 05 06 pm](https://user-images.githubusercontent.com/1861171/30300720-0544bbd8-970b-11e7-824e-20b2ddab90d7.png)

### Delete kittens breadcrumb from search
![screen shot 2017-09-11 at 4 04 07 pm](https://user-images.githubusercontent.com/1861171/30300706-ed74b0e4-970a-11e7-8a9e-9125d0dcfef0.png)

**Comment by jvine** [comment]
Highlighted message on the no results page, either in the Modify block or at the top in the Flash area:

> An empty search is not possible in articles+. Enter a keyword to start your search.

![screen shot 2017-09-11 at 4 23 20 pm](https://user-images.githubusercontent.com/6945691/30301195-1862b2da-970e-11e7-8e55-130506046e16.png)
