### ISSUE TITLE
We are loading two different Source Sans Pro fonts, can this be reduced to 1 request?

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/SearchWorks#1825]
![screen shot 2017-11-02 at 7 59 31 am](https://user-images.githubusercontent.com/1656824/32325048-caac0dc0-bfa3-11e7-907d-dbae85e5a609.png)

**Comment by marlo-longley** [comment]
[This commit](https://github.com/sul-dlss/SearchWorks/commit/37790aa35bb9f867ceae8bfe9e8313ae0df46028#diff-72f7f42c43936b81b419c74a5025def5656743492126174315915fa24b85ae0c) from about a year after this ticket was filed switched the font loading to use [Google Web Font Loader](https://github.com/typekit/webfontloader) rather than the Google Fonts API. We no longer redundantly load the normal/400 weight font as in this screenshot. We do make 2 calls now, but they are for 2 different fonts. I think it's safe to close this ticket.


<img width="273" alt="Screen Shot 2022-08-12 at 15 58 32" src="https://user-images.githubusercontent.com/1328900/184686816-39ccdc1a-264e-4164-8fa8-3e6c993fcccb.png">
