### ISSUE TITLE
SW Solr Users feedback: Match ranking explanation

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/SearchWorks#1919]
Issue: This is the first search Ive done where the results from current Searchworks made more sense. In current searchworks result number 11 is ckey 8220230 which is one I would have expected to be one of the first results - since it is about constitution and president. I don't see this result in the first 2 pages of results (unless I'm missing it). 	 https://sw-relevancy-new.stanford.edu/catalog?utf8=%E2%9C%93&search_field=search&q=united+states+constitution+AND+president*+	

Discussion: Worse (Ranking): Explanation, exact matches are at top, stemmed version below it, hence the change.

Work needed: write-up and/or documentation on why this change occurs for reporting back to the super users.

**Comment by shelleydoljack** [comment]
The current specification is to boost title matches above matches in other fields and exact matches should appear first with the stemmed versions below it. The results of this search in "new" SearchWorks shows that exact matches are at the top with the stemmed versions below it; it performs to the specification. However, we notice that the order of the search terms in the results is not the same. We get lots of records with "Constitution of the United States" in the title in "new" SearchWorks rather than "United States Constitution." By putting quotation marks around "united states constitution" in our search we will get records with the search terms in the order we expect them to be in the results. 

Why does ckey 8220230 not show up in the top 20 in "new" SearchWorks? The title field for ckey 8220230 is "the constitutional presidency" while the search terms are "united states constitution AND president*". In "new" SearchWorks, the top 20 results all have the search terms, in some order, in the title fields followed by stemmed versions. In "current" SearchWorks, the stemmed versions of some of the search terms (e.g. presidency) are getting into the top 20 results.

**Comment by cmh2166** [comment]
Thanks, @shelleydoljack
