### ISSUE TITLE
SW Solr Users feedback: Series or Journal Title prioritization

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/SearchWorks#1925]
Prioritization of certain titles is a concern that we *might* need to address within work cycle. If not feasible without boutique coding (specific to each of these titles), needs to be kicked to Gryphon-*. Titles relevant for this:
- Time (Test 1. Journal searches (I chose 10 most popular journals). Different: Time. Ckey 398734 is result #12 in production and #13 in test. )
- Out of my 30 tests for common journal/periodical/newspaper titles this was the only result I was not satisfied with. Title=independent. After the 8th result, the test environment relevancy decides a different stem, "independence" is more relevant than other titles (of which there are many!) that include the exact word form "independent". I can see where boosting different stems can be helpful -- do we assume most users do not actually know which words they want to search for? -- but I found it jarring to suddenly be in the midst of a bunch of "independence"s when I searched for "independent," when I'm only interested in "independent". That's it for my testing feedback. As I mentioned, the lion's share of my tests returned basically the same or slightly improved results, and the inclusion of MODS records (on purpose, I hope) in results sets was fantastic.
- Test 1. Journal searches (I chose 10 most popular journals). Different: Nature. Ckey 3195844, which is the most relevant result, is currently #4. In the test environment, it is #12.

**Comment by mejackreed** [comment]
Addressing these individually:

 - Not something we can address and needs to be discussed at Gryphon-*
 - The  Solr 6.6.1 approach seems to preference stemmed values with leading matches rather than unstemmed with more phrase words (Independence over The Independent, Independence: a story.. over The Independent) https://sul-solr-tester.stanford.edu/searches/559347 . It's unclear if we can actually address this.
 - With so many items having the title "Nature" I'm not sure we can increase the relevancy here without direction from Gryphon-* on  such a broad search term.

**Comment by cmh2166** [comment]
Great, thanks @mejackreed
