### ISSUE TITLE
Law - Displaying public notes in subfield z

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#1940]
https://jirasul.stanford.edu/jira/browse/SW-1873

**Comment by jvine** [comment]
**Background**

1. Normal Stanford-only e-resources have a subfield z that includes some variation of "z| Available to Stanford-affiliated users". When we find that text, we display a red S with the text as a tooltip. Example: https://searchworks.stanford.edu/view/12798015
2. There's some secondary condition where, if there is a red S and a supplemental subfield z, we do display the text of the second subfield z. Example: [TBD]
3. Otherwise, subfield z text is suppressed from display because it tends to include wacky things like "Requires IE6". 

**New situation**

Law School has licensed resources that are more restricted than Stanford-only. The text they use in subfield z (z| Available to Stanford Law School community.) is not caught by the regular expression and doesn't get the red S. We currently display no subfield z text for their records. Example:
https://searchworks.stanford.edu/view/11354015

**Desired outcome**

For Law School records only:
- [ ] If there is standard red S text ("Stanford-affiliated users"), retain current behaviour.
- [ ] Otherwise, display all subfield z text.

![screen shot 2018-10-16 at 5 28 03 pm](https://user-images.githubusercontent.com/6945691/47054824-eeeb4480-d168-11e8-8b96-6e0653e9579e.png)

**Comment by jkeck** [comment]
This is blocked until we stop parsing MARC in the results.
