### ISSUE TITLE
No results should show links to WorldCat, HathiTrust, ILL

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#1941]
https://jirasul.stanford.edu/jira/browse/SW-1909
https://jirasul.stanford.edu/jira/browse/SW-1930

**Comment by jvine** [comment]
Design also addresses feedback from various sources around the "modify" options, static/incorrect chat hours, missing formatting, and order of items in single-column view.

- [ ] Change the wording order of the "Modify your ... search" heading
- [ ] Add this text as the first item in the "Modify" list:  `Check spelling, or use fewer words to start.`
- [ ] Simplify the formatting of the suggested searches:
   - use `<ul>` instead of `<dl>`
   - drop "Your current search"
   - add styling around the search terms to call them out
   - use the same styling for the > as in the actual search breadcrumb. 
- [ ] insert the appropriate mini-bento after the "modify" section
- [ ] add a "More options" section with these links:
   - ILL:  https://sulils.stanford.edu/
   - **catalog only** WorldCat:  Send search terms to https://www.worldcat.org 
   - **catalog only** HathiTrust:  Send search terms to https://catalog.hathitrust.org
   - **articles only** Databases:  https://searchworks.stanford.edu/databases
   - More search tools:  current link already on the no-results page
- [ ] Move the Chat link to the left sidebar and show live IC hours (note that this section is only visible when on campus or via VPN)
   - InfoCenter link:  https://library.stanford.edu/libraries/green/information-center
   - InfoCenter hours:  https://library-hours.stanford.edu/libraries/green/locations/information-center
   - do not disable the InfoCenter link when Chat is offline
- [ ] Remove the extraneous `<h3 class="sr-only panel-title">Search context</h3>` from the sidebar

### Catalog mockup
<img width="1232" alt="no result - catalog - chat open" src="https://user-images.githubusercontent.com/6945691/45854009-98235400-bcfd-11e8-8fa0-ce3adf312958.png">

### Articles mockup
<img width="1222" alt="no result - articles - chat closed" src="https://user-images.githubusercontent.com/6945691/45854010-98bbea80-bcfd-11e8-831f-286a574f6b09.png">

### Text for copy/paste
> Check spelling, or use fewer words to start.

> Chat reference is available during normal Information Center hours.

> Interlibrary loan
> For Stanford affiliates. We can get just about anything.

> WorldCat
> Search other libraries nearby and worldwide.

> HathiTrust
> Millions of digitized resources; especially helpful for government documents.

> Databases
> Search directly in a topic-specific database.

> More search tools
> Links to help you find images, data, dissertations, archival materials, and more.

**Comment by jvine** [comment]
Styling for Modify section:

Bubble around search term:
```    
    padding: 4px 10px;
    border-radius: 15px;
    margin: 0 5px;
    border: 1px solid #8c1515;
```
Margin between list items:
```
    margin-bottom: 15px;
```
