### ISSUE TITLE
record selections without login

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#1942]
Users should be able to select records and email them to themselves without having to authenticate.

https://jirasul.stanford.edu/jira/browse/SW-1978

**Comment by jvine** [comment]
Something like this?

<img width="605" alt="screen shot 2018-09-25 at 9 47 19 am" src="https://user-images.githubusercontent.com/6945691/46029368-11c59400-c0a8-11e8-9f60-ea1572c965c2.png">

In other words, Captcha for non-authenticated users, not present for authed users. Will this be enough? 

Alternatively - there was speculation that the form was extra-appealing to spammers because of the "email from" field. Do we have a sense of how often this is used? (It's for librarians sending lists of books to patrons.) I wonder if we could limit that field to logged-in users, and add a honey-pot? 

<img width="604" alt="screen shot 2018-09-25 at 9 55 17 am" src="https://user-images.githubusercontent.com/6945691/46029770-2a827980-c0a9-11e8-939f-79270d92c6bb.png">

**Comment by jkeck** [comment]
I don't think disabling the `Email from` field for anonymous users helps us much, if at all.  It makes it potentially more useful to a spammer, but doesn't diminish the potential damage they can do w/ the form.

**Comment by jvine** [comment]
Okay. I'm good with the non-authed Captcha then.

**Comment by jkeck** [comment]
@jvine:

In doing this work, I'm going to take out the previous spam capturing honeypot functionality from the email form.

We also use this same field in the feedback form and I believe we have had trouble w/ it in the past WRT how browsers' autocomplete interacted w/ that field.  Should we also take the same approach w/ Feedback (or just leave as-is for now)?

**Comment by jvine** [comment]
I don't believe we are still having the problem with autocomplete, but I think it was a slightly hacky workaround to make Chrome not recognize it as an autocompletable field. reCAPTCHA is probably more robust. As much as I'm not a fan, we might as well be consistent.
