### ISSUE TITLE
866 mhold should wrap

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/SearchWorks#2021]
Force this field to wrap even if there are no spaces

<img width="582" alt="screen shot 2018-10-02 at 1 38 58 pm" src="https://user-images.githubusercontent.com/5402927/46375545-92f0ce00-c648-11e8-85f7-b2f70482fe4c.png">
<img width="658" alt="screen shot 2018-10-02 at 1 39 11 pm" src="https://user-images.githubusercontent.com/5402927/46375546-9421fb00-c648-11e8-9e91-ae29beb6ef3d.png">

https://searchworks.stanford.edu/view/8838463

**Comment by jvine** [comment]
We currently add `<wbr>` to the MHLD summary after a dash, but there are still overlong strings between dashes with no breaking characters, that cause the text to overflow the sidebar and overwrite the metadata to the right. Previously we considered adding a space to the data after every comma, but this was rejected because it was counter to MHLD standard. That objection has been dropped, and g-search is in favour of option 1 below.

1. Add a space after every comma in the MHLD summary, so we get something that looks like this:
   <img width="335" alt="screen shot 2018-10-02 at 2 56 56 pm" src="https://user-images.githubusercontent.com/6945691/46565846-35b77f80-c8c9-11e8-9daa-411bfae73277.png">

or failing that...

2. Add `word-break: break-all;` which will occasionally give a bad outcome in a different, less obvious way (i.e. breaking in the middle of a number) like this:
   <img width="346" alt="screen shot 2018-10-02 at 2 55 02 pm" src="https://user-images.githubusercontent.com/6945691/46565852-5e3f7980-c8c9-11e8-8f5e-692d51046ec9.png">

Option 1 vastly preferable.
