### ISSUE TITLE
SDR display - Results view design

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/SearchWorks#2023]
https://xd.adobe.com/view/8afda751-8b8e-4317-781f-1c8406c157a8-fccc/?fullscreen

**Comment by jvine** [comment]
Summary of changes in the mockups:
1. Format metadata `<dl>` as in articles+
2. Use standard Description label instead of resource type value; add resource type value to the `<dd>`
3. Locate Summary with metadata; use "more…" expand pattern (as in articles+) 
4. Change metadata order to
   a. Description
   b. Summary
   c. Finding aid
   d. Appears in
   e. Collection
5. Change Online button to badge/label; use "more…" expand pattern (as in articles+) 
6. Use standard button styling for Check availability and Course reserve (expand-behaviour remains the same)
7. Move title-level online badge from end of title to beginning, before result number
8. If there is a title- level badge, additional online links are labelled "Also online at" instead of a second badge
9. Remove redundant "view all # items" links for collection records
10. Move "Also online at" links after collection preview

**Comment by jvine** [comment]
effects to Brief and Gallery view, and Browse nearby
