### ISSUE TITLE
Implement Schema.org Dataset type for our Datasets

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/SearchWorks#2041]
(Note that #2029 is a pre-requisite to this work)

We have been asked to take a bit of a deeper dive into a known use-case for producing Schema.org representations of our objects, which is for Datasets.  Google will soon be providing rich display of certain types of data (e.g. tabular data) directly in Search Results. In anticipation of this feature, we would like to represent our Datasets more richly in Schema.org output.

It is worth noting that according to [Google's Documentation](https://developers.google.com/search/docs/data-types/dataset):
> This feature is in pilot, and you may not see rich results for datasets yet. However, we recommend that you add dataset structured data to your site in preparation for new dataset features in Search results.

We can decide how deep of a dive we want to take with this.  At the very least, we'll most likely want to provide the  a `DataDownload` in the Dataset's  `distribution` property.  An open question WRT how much data we include is do we want to include SearchWorks as a `DataCatalog`  in the `includedInDataCatalog` property.  We could go as far as publishing some some simple tabular data as a `csvw:Table` (particularly if we want that data to show up), but could easily see that falling out of scope and/or being split off into a separate issue.
 
**Potentially helpful links:**
* https://www.blog.google/outreach-initiatives/google-news-initiative/making-it-easier-discover-data-search/
* https://developers.google.com/search/docs/data-types/dataset
* https://search.google.com/structured-data/testing-tool

**Comment by mejackreed** [comment]
Part of this ticket also needs to communicate to difficulties with other types of data, difficulties with our metadata schema, and opportunities to move this forward in the future.

**Comment by mejackreed** [comment]
Additional implementation of other types of content might get complicated, but could be done by defining the following:

 - A consistent understanding or mapping of what constitutes a "DataSet" in SDR content. https://github.com/sul-dlss/searchworks_traject_indexer/pull/229 was able to be done because all of "content_type=geo" is inherently a "dataset". How else can we determine this? Likely some subset of "content_type=file" with certain resource file types enabling this functionality. Would the presence of a CSV file automatically determine this to be a dataset? 
 - Easier mapping of dates. If we could provide (instead of having to parse and determine) ISO 8601 dates (see https://developers.google.com/search/docs/data-types/dataset)
 - What else?

**Comment by hannahfrost** [comment]
@mejackreed I'm chiming in late to acknowledge and appreciate your comments above about difficulties with our schema, what constitutes a dataset, and what else we might want to consider going forward. I'm flagging this as something that SUL data stakeholders can help with in the future.

**Comment by mejackreed** [comment]
Thats great, thanks @hannahfrost . Let me know if you want to chat more about the complications.
