### ISSUE TITLE
Add Schema.org VideoGames

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/SearchWorks#2064]
Based off discussions over email w/ Greta de Groat, adding support for VideoGames is desired.

Perhaps? 

![image](https://user-images.githubusercontent.com/1656824/47161044-0b40cb80-d2a6-11e8-9962-30df0ab2a20a.png)

**Comment by gdegroat** [comment]
Hi.  Unfortunately Genre:Video games is not as straightforward as you would think it should be.  There has been major changes in the way genre is handled in MARC cataloging over the years (earlier coded as subject and later as genre), as well as big changes in the way video games have been cataloged.  If you had direct access to the MARC record, the single most reliable bit of data would be MARC 008/26 with value g.  But there are some records without that.  Is it possible to use a keyword within Genre or Subject?  Because another option would be to combine  Resource type: Software/Multimedia and the word "games" anywhere in a Subject or Genre text string.  Again it wouldn't get everything (many got cataloged as "interactive multimedia" instead of games), but it should get most.

By the way, i think that MARC 008/26 is driving the dataset facet for datasets represented by MARC records.  The Genre and/or Subject strings for those are Databases, not Datasets.  Looking at SearchWorks, i see that the ones cataloged in MARC are showing up in both the Datasets and Databases facets, while the majority of things in the Datasets facet look like they have MODS records generated during the SDR process.  Interesting, these are things i never see.

thanks
greta
