### ISSUE TITLE
Missing records in Articles give 500 error rather than 404 ??

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#2120]
https://searchworks.stanford.edu/articles/edsgao__edsgcl.151592087
https://searchworks.stanford.edu/articles/eric__EJ739770

These articles appear to have been removed from the Ebsco database. They give this error:
<img width="400" alt="screen shot 2018-11-07 at 10 06 49 am" src="https://user-images.githubusercontent.com/6945691/48150964-f0de8a00-e274-11e8-8a6e-0ba04655be49.png">

When I would have expected this:
<img width="400" alt="screen shot 2018-11-07 at 10 07 00 am" src="https://user-images.githubusercontent.com/6945691/48150980-f936c500-e274-11e8-8508-7fe3b101e980.png">

**Comment by jkeck** [comment]
Both of the URLs linked are giving that error because they are returning a 500.  There is a fix that will be released soon to address that. (currently deployed to stage)

It looks like Not found errors are actually thowing a BadRequest error from the API, which we simply send back to the Articles+ home page w/ a not super helpful message: https://searchworks.stanford.edu/articles/blah__12345
