### ISSUE TITLE
Add Guides to mini-bento

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#2519]
<img width="787" alt="SW mini bento" src="https://user-images.githubusercontent.com/6945691/89927583-60587a80-dbbb-11ea-9877-fe794554682f.png">

### Modify the Articles section

- remove the `<dl>` structure and `<dt>` text. Turn the `<dd>` list of facets into a `<ul>` with `<li>` styled as `inline-block`
- set the font size of the links to `1.125em` (which doesn't seem to be defined in SW but should be `h5, .h5`)
- apply `color: #737373` to the "Journal articles..." tagline. (Also not defined in SW variables? but same colour as `<dt>`.)

### Parallel changes to Catalog section when searching Articles

<img width="784" alt="Screen Shot 2020-08-11 at 10 09 43 AM" src="https://user-images.githubusercontent.com/6945691/89927209-d4dee980-dbba-11ea-9db5-be3ee38e5837.png">

### Add the Guides section

Listing 3 titles, _without_ summary, _without_ expand-o feature. 

- border between the sections is `1px solid $cloud`
- section title and tagline styled as with Articles+
- guide titles are in `<ol>` with font-size `1.125em`
- link to native Guides search is located in upper right, parallel to "See... results" button
- font size of link is `.h4`

**Comment by jkeck** [comment]
@jvine should we show this block even if there are no guides present for the search?

**Comment by jkeck** [comment]
@jvine when you say `.h4` what do you mean?  I ask because in SearchWorks the font-size for h5 is 1em not 1.125em (which you describe above).

Our (relevant) heading font sizes are:
- h3: 1.383em (what the Articles+ & Guides headings are styles as)
- h4: 1.215em
- h5: 1em

If we make the facet/guide links styled as h5, they will be the same size as the base font (which would have no affect).  If we style them as h4, then there is no current heading size between them and the Articles+/Guides headings for the `Search "foo" in all guide pages` to use.

What do?

**Comment by jvine** [comment]
> @jvine should we show the guides section of the block even if there are no guides present for the search?

No.

> What do?

Yeah, sorry, this is a bit buried.

h5 is currently 1em, because I think that's the Bootstrap default and we never customized that far down the tree. I would like it to be 1.125em, because that's a useful size for a variety of things, while 1em is not. This new size (`.h5`, not semantic `<h5>`) applies to the facet links in the Articles section, and Guide titles in the Guides section. 

Does that clarify?
