### ISSUE TITLE
Articles+ full text pdf downloads, authentication and an "S" icon

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#2771]
This might need to be split into multiple tickets but we continue to get reports from users that are logged into SearchWorks, using Articles+ and attempt to download a full text pdf.  

1. They see the message "Sorry, the PDF download was not successful because you are currently in guest mode. Log in to try the download again." even though they are logged in.  
2. We don't indicate to the user that authentication is required for these resources. Eric told Chris in August 2021 that full text pdf downloads will need authentication. Chris wanted to do some more due diligence to make sure that's true (e.g. open access databases)
3. Whatever we can determine needs auth should probably have the "S" added 

Example records: 
https://searchworks.stanford.edu/articles/edsbro__edsbro.A236553399
https://searchworks.stanford.edu/articles/edsbl__vdc.100092542464.0x000001

Jira ticket: [SW-4029 ](https://jirasul.stanford.edu/jira/browse/SW-4029)

**Comment by camillevilla** [comment]
![Screen Shot 2022-01-18 at 4 12 37 PM](https://user-images.githubusercontent.com/5402927/150039221-e649e1e8-e521-469a-ac36-16d1a7215957.png)
The "S" icon is now displayed in PR #2796, @corylown asks: should we also be displaying the "S" in the index view? I did a little research into how we're using the icon so that @saseestone (or @ggeisler in her absence?) could make the call.

## SearchWorks
In SearchWorks, we currently use the "S" icon in a limited number of places. They're all links out to services on other Stanford websites that are only available to Stanford affiliates.
![Screen Shot 2022-01-18 at 4 04 57 PM](https://user-images.githubusercontent.com/5402927/150041392-83ce7ac5-5590-4405-8ee3-5ec01597479b.png)
![Screen Shot 2022-01-18 at 3 56 30 PM](https://user-images.githubusercontent.com/5402927/150041396-b2ba5d28-276e-4b98-9fb4-2a670e5bf3b2.png)

Meanwhile, the majority of things in Articles+ hand off to auth. Here's a useful example search:
https://searchworks.stanford.edu/articles?q=Uptake+of+HPV+vaccine&search_field=search
- View / download PDF 
- View on content provider's site

"Find full text or request" SFX links don't require auth, but they may or may not redirect to sources that require auth. 


## EarthWorks
In Earthworks we have the "S" icon sprinkled all over to distinguish Stanford-contributed data from other institutions' data. 
![Screen Shot 2022-01-18 at 4 02 28 PM](https://user-images.githubusercontent.com/5402927/150041565-89c3bbe5-563b-4fea-beae-da262b12cead.png)

**Comment by cbeer** [comment]
We also use the S in searchworks for Stanford-only e-resources:

<img width="724" alt="Screen Shot 2022-01-19 at 07 24 03" src="https://user-images.githubusercontent.com/111218/150161082-6b4bc8ad-7d59-41f3-8db4-b2395cc6205c.png">

So we're not above scattering it everywhere 🤷‍♂️

**Comment by ggeisler** [comment]
Can someone provide a URL to an index view containing resources that are relevant to the "S" or not question?

**Comment by cbeer** [comment]
https://searchworks.stanford.edu/articles?q=International+Index+to+Music+Periodicals+Full+Text&search_field=search

The third hit has a link "View on content provider's site" that bounces you through webauth (if you're not on campus/VPN/etc):

![Screen Shot 2022-01-19 at 09 06 39](https://user-images.githubusercontent.com/111218/150179453-51c39de0-b9b9-45c4-b530-948196bf9989.png)

**Comment by ggeisler** [comment]
I would be happy if we want to wait and get @saseestone's thoughts on this (or hear from anyone who thinks I'm missing something relevant), but from my perspective the answer seems pretty clear: we should apply the Stanford "S" icon anywhere the link would lead to requiring the user to authenticate (if they are not already). By not doing so, we're withholding useful information (especially to the non-Stanford users, who won't find out they can't get the item until they follow the link) and not reinforcing our pattern for representing authentication-required resources (by using our pattern inconsistently).

Earthworks creates an exception to the use of the "S" icon, since there it's used for institution identification rather than authentication-required identification, but I think that is our only big exception (I could be completely wrong on that) and I'd say it's something to deal with in Earthworks rather than a reason not to stick to our pattern everywhere else.
