### ISSUE TITLE
evaluate usage of FOLIO RTAC API for availability lookups

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/SearchWorks#2905]
SearchWorks currently does live availability lookups for items using the `vufind.pl` script called from the `AvailabilityController` via ajax on each catalog index/show page. This script, in turn, calls Symphony web services to get the real-time availability info (but see https://github.com/sul-dlss/SearchWorks/issues/2871 which proposes making web services calls directly rather than using `vufind.pl`).

FOLIO offers a **R**eal-**T**ime **A**vailability **C**heck (guessing on the "C" part here) API. We need to determine whether the information provided by this API is sufficient for it to replace the current combo of symws/vufind (or symws alone).

This issue also has bearing on https://github.com/sul-dlss/searchworks_traject_indexer/issues/639: we need to ensure that instance IDs from FOLIO make it into traject so that SearchWorks can provide them when making RTAC calls. If RTAC has problems, we may also need to provide additional fields to SW via traject to assist in determining availability and/or location.

See the second part of [this notebook](https://gist.github.com/jermnelson/bf8e78fdb9675cd877686cd26d253c5a) for an example query to the RTAC API and response.

**Comment by corylown** [comment]
- [FOLIO Wiki - RTAC - Real Time Availability Checking](https://wiki.folio.org/display/FOLIJET/RTAC+-+Real+Time+Availability+Checking)
- [Real Time Availability Check version v1.5](https://s3.amazonaws.com/foliodocs/api/mod-rtac/rtac.html#rtac__id__get)
- [Real Time Availability Check version v1.0](https://s3.amazonaws.com/foliodocs/api/mod-rtac/rtac-batch.html#rtac_batch_post)
- [Edge API - Real Time Availability Check](https://s3.amazonaws.com/foliodocs/api/edge-rtac/edge-rtac.html#edge_api___real_time_availability_check)](https://s3.amazonaws.com/foliodocs/api/edge-rtac/edge-rtac.html#rtac__instanceid__get)

**Comment by corylown** [comment]
There will be more to do here as we get closer to an implementation.

The folio-tasks repository includes tasks for interacting with FOLIO, including making requests to the RTAC-batch API

```
folio-tasks % ruby bin/folio_post.rb '/rtac-batch' './batch.json'
```
Where the `batch.json` file contains:

```
{"instanceIds": ["b6919f84-f7f3-5957-84d6-fcf603aaacbb"],"fullPeriodicals" : "false"}
```

Currently, the `app_discovery` user does not have permission to access `rtac.batch.post` on `okapi-dev.stanford.edu`, but more testing can take place once these permissions are granted.

Similar to the `vufind.pl` script used by SearchWorks to request availability information in batches (via bib ID) from Sirsi, the RTAC-batch API will accept requests for more than one Instance ID (a bib record's FOLIO UUID) at a time.

The `AvailabilityController` in SearchWorks accepts requests like this, where the `ids` are bib ids.

https://searchworks.stanford.edu/availability?ids[]=13408079&ids[]=10828538&ids[]=14048370

And returns a response (assembled from the response from `vufind.pl`) like this:

```
[{"barcode":"36105230607371","due_date":null,"current_location":null},
 {"barcode":"36105034793864","due_date":"9/26/2022","current_location":null},{"barcode":"36105217715486","due_date":null,"current_location":"Checked out - Overdue"}]
```

The response content from the RTAC batch availability request is documented here: https://s3.amazonaws.com/foliodocs/api/mod-rtac/rtac-batch.html#rtac_batch_post

Things we'll need to keep in mind:

- Instead of bib ids the requests to RTAC batch expect FOLIO Instance UUIDs and we will need to store these in Solr in order to make these requests.
- The RTAC batch availability response uses the item UUID to identify each item rather than the barcode. We will need to store FOLIO item UUIDs in Solr in order to match the RTAC response to each item.
- The properties that may be returned for each item are:
  - id
  - location
  - callNumber
  - status
  - dueDate
  - volume
  - temporaryLoanType
  - permanentLoanType
- It appears that the `id`, `dueDate`, and `status` fields will provide the information we need to display real-time availability in SearchWorks, but more investigation will be needed once data is migrated to FOLIO and the data model, partciularly for status and location are better defined.
- We will need to test performance of the RTAC batch availability services to determine if it is fast enough for our purposes.

**Comment by shelleydoljack** [comment]
I added the RTAC permissions to dev and test. It should work now. The example batch.json with instance ID b6919f84-f7f3-5957-84d6-fcf603aaacbb returns:
```
{
    "holdings": [
    ],
    "errors": [
        {
            "message": "Instance b6919f84-f7f3-5957-84d6-fcf603aaacbb can not be retrieved",
            "code": "404"
        }
    ]
}
```
Here is an instanceId in dev that returns some holdings: 49f63620-7d57-570b-a006-84273dff89ad

**Comment by corylown** [comment]
Unclear how this will translate to production, but an RTAC-batch request for 10 instance IDs takes about 1600ms (if I'm reading the gtime output correctly).

```
{"instanceIds": ["2a0e9c8b-33b1-583c-8fbe-8effdfcabcd9","b92d6d62-2768-55db-af57-8441f9037b50","58f102ed-8781-5765-9837-6607111d0434","5e833b41-b222-5edf-a9e0-437a3b2ec2bb","28e98be0-cb68-517f-b656-fe585867f561","bfdcce7d-efaf-5809-ada0-17fb86b7818a","7a6bdad3-088a-5cdc-bed1-d112f822c0db","0a2dad05-e325-57ff-a61a-4cd34c133e2f","e74bff48-ed97-5385-ba74-510d1c8a9bae","9cb1a2e2-3d26-5cb1-ae3c-c91043b35acf"],"fullPeriodicals" : "false"}
```

```
folio-tasks % gtime ruby bin/folio_post.rb '/rtac-batch' './batch.json'
{"holdings"=>
  [{"instanceId"=>"0a2dad05-e325-57ff-a61a-4cd34c133e2f",
    "holdings"=>
     [{"id"=>"9c130866-f1a4-53fb-b390-30ac35b00388",
       "location"=>"Green Library Stacks",
       "callNumber"=>"BQ974 .A3588 B73 2013",
       "status"=>"Available",
       "permanentLoanType"=>"Can circulate"}]},
   {"instanceId"=>"28e98be0-cb68-517f-b656-fe585867f561",
    "holdings"=>
     [{"id"=>"2a93bc1d-ad64-541a-bb9c-0f2d49f5f10a",
       "location"=>"Green Library Stacks",
       "callNumber"=>"GV1788.6.S36 D86 1985",
       "status"=>"Available",
       "permanentLoanType"=>"Can circulate"}]},
   {"instanceId"=>"2a0e9c8b-33b1-583c-8fbe-8effdfcabcd9",
    "holdings"=>
     [{"id"=>"dc55e2d7-0c34-5fa2-8ff5-6592dd283882",
       "location"=>"Green Library Stacks",
       "callNumber"=>"BF108 .N6 A38",
       "status"=>"Multi"}]},
   {"instanceId"=>"58f102ed-8781-5765-9837-6607111d0434",
    "holdings"=>
     [{"id"=>"24ca56be-ee43-5cea-a978-172d3dc3903a",
       "location"=>"Green Library Stacks",
       "callNumber"=>"PS3537.A832 A73 1982",
       "status"=>"Available",
       "permanentLoanType"=>"Can circulate"}]},
   {"instanceId"=>"5e833b41-b222-5edf-a9e0-437a3b2ec2bb",
    "holdings"=>
     [{"id"=>"842b77be-5d98-5c42-8b32-e9122ea52c47",
       "location"=>"Green Library Stacks",
       "callNumber"=>"DD804.66 .W45 S38 2012",
       "status"=>"Available",
       "permanentLoanType"=>"Can circulate"}]},
   {"instanceId"=>"7a6bdad3-088a-5cdc-bed1-d112f822c0db",
    "holdings"=>
     [{"id"=>"c3640dbf-9464-5aa8-a400-b59448107f98",
       "location"=>"Green Library Stacks",
       "callNumber"=>"BF637 .M4 A38 2014",
       "status"=>"Available",
       "permanentLoanType"=>"Can circulate"}]},
   {"instanceId"=>"9cb1a2e2-3d26-5cb1-ae3c-c91043b35acf",
    "holdings"=>
     [{"id"=>"5e7cdccf-f87c-5989-94e7-ea7b0a0d596b",
       "location"=>"Green Library Stacks",
       "callNumber"=>"HX828 .J46 2014",
       "status"=>"Available",
       "permanentLoanType"=>"Can circulate"}]},
   {"instanceId"=>"b92d6d62-2768-55db-af57-8441f9037b50",
    "holdings"=>
     [{"id"=>"3a9dfb22-8c93-5850-b427-e5570bb21fa4",
       "location"=>"Green Library Stacks",
       "callNumber"=>"PS3537.A832 M3 1985",
       "status"=>"Available",
       "permanentLoanType"=>"Can circulate"}]},
   {"instanceId"=>"bfdcce7d-efaf-5809-ada0-17fb86b7818a",
    "holdings"=>
     [{"id"=>"dc59e825-4f0d-5891-9b61-b64dffac4440",
       "location"=>"Green Library Stacks",
       "callNumber"=>"HD6073 .B892 A9 2013",
       "status"=>"Available",
       "permanentLoanType"=>"Can circulate"}]},
   {"instanceId"=>"e74bff48-ed97-5385-ba74-510d1c8a9bae",
    "holdings"=>
     [{"id"=>"d3a50bd2-9a2e-595c-a5dc-03246f44b3f0",
       "location"=>"Green Library Stacks",
       "callNumber"=>"BQ9408 .B833 2016",
       "status"=>"Available",
       "permanentLoanType"=>"Can circulate"}]}]}
0.55user 0.25system 0:01.60elapsed 50%CPU (0avgtext+0avgdata 34112maxresident)k
0inputs+0outputs (0major+8715minor)pagefaults 0swaps
```

**Comment by cbeer** [comment]
With the data in searchworks-folio-dev, this work might be unblocked and could inform additional indexing (or index-land pre-processing).

**Comment by thatbudakguy** [comment]
overview of possible values for "status" coming from RTAC, and what FOLIO workflow/action triggers that status: https://lotus.docs.folio.org/docs/platform-essentials/item-status/itemstatus/#currently-implemented-item-statuses

**Comment by thatbudakguy** [comment]
some thoughts from pairing today:
- we will update searchworks's `LiveLookup` to hit the RTAC API instead of vufind.pl
- we will need to ensure that item UUIDs are injected into the page so that searchworks can find the right place in the document to add the availability information
- currently the barcode is used and is injected into a data attribute; we will replace this with item UUID since RTAC doesn't return barcodes
- do `status` values correspond to things we actually want to show to patrons, or will we need to do some kind of mapping/lookup to a different value? or would we just ask libsys to change the naming of the statuses in FOLIO-land?

**Comment by thatbudakguy** [comment]
closing; prototyping implementation on #2964
