### ISSUE TITLE
Design improved bound-with display in Searchworks

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#3099]
Bound-withs are currently recorded in a 590  field and displayed a couple places in the searchworks display

(e.g. https://searchworks.stanford.edu/view/3142831)

FOLIO changes the way bound-with data is recorded (to be more structured?), so we have an opportunity to make this relationship clear to our patrons.

Figure out:
1) how bound-with data is represented in folio
2) how to best represent the data in searchworks (and requests + mylibrary?)
        - in the upper metadata section? 
        - in the library/location access panel?
        - in the body of the record?

**Comment by marlo-longley** [comment]
[This record](https://folio-test.stanford.edu/inventory/view/37486ca7-dbb1-5d37-85d6-578f91196074?qindex=all&query=Report%20of%20the%20committee%20of%20investigation%20Nashua) in folio-test seems to be the equivalent of the one referenced in the comment above. Its parent record that it is bound with in folio-test should be [here](https://folio-test.stanford.edu/inventory/view/37486ca7-dbb1-5d37-85d6-578f91196074?qindex=all&query=Report%20of%20the%20committee%20of%20investigation%20Nashua). 

I don't see any bound-with data for either record in folio. Is this something that exists, or that needs to be investigated in order to index?

**Comment by saseestone** [comment]
Marlo - I don't know if the example you provided above is on the list of bound-with titles that Alissa provided us.  That list is here: https://folio-test.stanford.edu/inventory?filters=holdingsType.5b08b35d-aaa3-4806-998c-9cd85e5bc406&segment=holdings&sort=title

In the FOLIO UI: Here's a link to the holdings record of a [bound-with record](https://folio-test.stanford.edu/inventory/view/18b00ef2-827e-5554-8dd4-f0c897831b77/18d08faa-4e85-5e3b-bc4d-6537a8fb3b43?filters=holdingsType.5b08b35d-aaa3-4806-998c-9cd85e5bc406&segment=holdings&sort=title) from her list.

The parent record id appears at the very bottom of the bound-with holdings record:
![image](https://user-images.githubusercontent.com/14897546/232092935-2581c800-3dd9-44a0-8dd0-cc11586849d5.png)

Here's a link to the [parent record](https://folio-test.stanford.edu/inventory/view/d44dd4ed-6cc0-5c6a-b2a4-f48ea1ad46f7/d187d2ca-aab0-5d86-8de9-d675d7c31dcd/18340c01-9f72-5aea-8b05-69824e589072)

**Comment by marlo-longley** [comment]
@saseestone Thanks!! I didn't know where to start with this so this is super helpful.

**Comment by marlo-longley** [comment]
Potential good/new UX flow: "request" button in child, that sends a request for parent, because we have a data model in FOLIO that might tell us more.

**Comment by marlo-longley** [comment]
We got to parity with the current SW display with the PRs linked above. The UI remains the same. Some notes on an improved UI that we can use in the future. Here are some notes on basic improvements in 2 areas of the SearchWorks UI.

![Screenshot 2023-06-02 at 16 27 40](https://github.com/sul-dlss/SearchWorks/assets/1328900/c1ae58e7-3030-49f9-88e4-4843e3b8a762)
1. The request button for SEE-OTHER bound with children. For FOLIO parity, we are creating "fake" SirsiHoldings with SEE-OTHER data. However in FOLIO this distinction doesn't exist. It's the SEE-OTHER note that is the trigger for the absense of a request button in a bound-with child, and causes this yellow-highlighted box with a link to the parent to be displayed. The SEE-OTHER note is applied when a bound-with child is located in SAL3. An improved UI would be, for all bound-with children, regardless of their location in SAL3, to display a request button in this place instead.

To achieve this, we need the request button to link to a request for the parent it. We now have most of the needed data indexed from FOLIO to put together the correct link. However, we need to somehow communicate to Requests that this is not a typical request for the parent item, but rather a request for one of its bound-with children. We need to figure out a good data connection (URL param?) for making this clear to Requests. Then, we need to display this information in Requests so that the user understands that, when they go to the counter to pick up their item, it will have the parent's title, etc.

2. The note is something that users find confusing / too much data. My understanding is that the last part of the note (item id) is something currently being used for the FOLIO migration and won't be present afterwards. But the text that reads `Copy 1 bound with v. 5, no. 1. [5488000](https://searchworks.stanford.edu/view/5488000) (parent record's ckey).` should be improved. It would be more helpful for the user if `5488000` was replaced with the title of the parent (keeping the link). 

To summarize, some basic first steps for improving the UI would be:
- Render a request button for all bound-with children that request their parents. Send extra data to Requests that this is a bound-with child request.
- Display new information to the user in requests about the nature of this bound-with item
- Remove overwhelming identifiers in the note content in SearchWorks and replace with the parent item's title

**Comment by shelleydoljack** [comment]
It might be worth following up with Metadata folks if they intend to keep adding 590 notes to boundwith child records once in folio-land. However, since Nolana does not support creating boundwith relationships via the UI, maybe they don't know yet. But there will be a time when having a 590 note in a MARC record is unnecessary.
