### ISSUE TITLE
Display the request button in Searchworks using the FOLIO circ rules

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/SearchWorks#3129]
Searchworks currently displays two different kinds of request buttons:
- location-level
- item-level

We display location-level request links if the library/location is "pageable" with circulating items (e.g. SAL3), or "mediated" (or "aeon") for library's like SPEC.

We display item-level request links if the item's current location is requestable (e.g. CHECKEDOUT, LOST, etc).

We're hoping [some of the data for determining which request button](https://github.com/sul-dlss/SearchWorks/blob/bc855902d11d1e573a9466b23e7083851bfbee7e/config/settings.yml#L133-L589) to show can be determined by [evaluating FOLIO's circ rules](https://github.com/sul-dlss/SearchWorks/issues/3100); see #3149.

At a high-level, we generally show a location-level request link if a patron can have the item retrieved from off-site or an non-public area (e.g. locked stacks, SPEC) in order to at least see it. Item-level request links are used if a specific item is unavailable when it would be accessible (e.g. in the stacks somewhere) but is temporarily unavailable (e.g. because it is checked out). The actual rules are [even more nuanced](https://docs.google.com/spreadsheets/d/1n1n_DxHI1nDZC2DecjiMeiafu9VqpM2jJcS5l1-azYA/edit#gid=1279865253).

We should show a [location-level request link](https://github.com/sul-dlss/SearchWorks/blob/master/app/components/location_request_link_component.rb) if:

- [x] the effective library/location has a request policy that allows paging for any of the material types/loan types in that location (for any patron group).
- [x] TODO: we're currently filtering by current location to remove location-level links if the current location doesn't allow paging... is this appropriately captured in the FOLIO circ rules?
  - Look in SW code and make sure all locations there are in circ rules.
  - I believe this means `Settings.disabled_current_locations` which means https://github.com/sul-dlss/SearchWorks/blob/master/config/settings.yml#L771-L776
  - Those locations were not translated to folio locations https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/translation_maps/locations.tsv and they look like they are probably item statuses, but I'm not sure which statuses those items would have been given. `SPEC-INPRO` is in the temporary locations.
  - So, no these aren't captured because we need to ensure "SPEC-COLL" items with certain statuses "Missing", "In-Process" are not requestable. 
  - Check to make sure there is a circ rule that says you can't request: https://folio-test.stanford.edu/inventory?filters=effectiveLocation.32bebe0c-a235-4689-8f8a-6cc0472e74b1&sort=title
  - Because of Aeon rules, circ rules are not helpful at all (https://searchworks-folio-dev.stanford.edu/view/14801865)
  - Items with equivalent current locations should not get the request links. 
  - Currently this is displaying a "Request with aeon", but it should not have any request button.
- [x] we're filtering out e.g. SEE-OTHER locations. is this appropriately captured in the FOLIO circ rules?
  - Serials still use a SEE-OTHER locations (bound withs are not using this in folio)
  - I believe this is nonrequestable_locations https://github.com/sul-dlss/SearchWorks/blob/18d42443941001f2e8c68a2173f2ad43b42b2761/config/settings.yml#L729-L733
  - We seem to be handling this case appropriately in FOLIO; most SEE-OTHER holdings don't have items and share the bound-with behaviors
- [x] does FOLIO give us anything to determine mediated or aeon pageability? 
- [x] Hopkins has some weird business logic that suppresses location-level pages if the item is available online or available from some other library. Presumably FOLIO can't do the latter, at least?
  - @saseestone says Hopkins doesn't feel like this is a priority to solve for right now.  They are interested in opening this up for now to see if this is still a problem.
- [x] does item status factor in at all? Perhaps all cases are already handled and we don't need to drop down to this? (table that maps FOLIO item statuses to allowed request types: https://wiki.folio.org/pages/viewpage.action?pageId=73532141)
  - Item status factors into which requests are allowed, and we have to check item statuses explicitly to determine if the status is appropriate for a page/hold/recall. FOLIO's mod_patron endpoint handles figuring out which requests should be placed.
  - there's something especially funny about the item status `Paged`; once an item has one page request placed, it gets the status `Paged` and cannot have another page request placed (even if only page requests are allowed)

We should show an[ item-level request link](https://github.com/sul-dlss/SearchWorks/blob/master/app/components/item_request_link_component.rb) if:
- [x] we're not showing a mediated or aeon page button
  - handled upstream when we check if the location-level button was already drawn
- [x] the effective library/location/material type/loan type has a request policy that allows holds or recalls (for any patron group)
    - and the item status is hold/recallable in FOLIO
- [x] validate whether the non-requestable locations or item on reserve logic is captured by FOLIO circ rules
  - these are locations, and can/should have appropriate circ rules applied
- [x] validate whether the `*-LOAN` location matcher is captured by the FOLIO circ rules.
  - Are there `-LOAN` locations in FOLIO? We suspect they are service points, which circ rules aren't aware of.
  - There is "awaiting delivery" and "awaiting pickup" is the item status that FOLIO uses for this case.
  - We're 80% certain that circ rules aren't part of -LOAN (because the FOLIO locations won't change), but Awaiting is still a valid item status, so we should be fine

Note: during migration, all items are marked as pageable. 

TODO:
- [x] switch aeon + mediation logic to use the item's permanent location (and falling back to the holding's temporary location)

**Comment by thatbudakguy** [comment]
See https://github.com/sul-dlss/SearchWorks/pull/3132 for the beginnings of work on this.

Here's some things we know about the function that selects the appropriate circ rule for requesting an item, currently called `CirculationRules::EvaluationService#rule_for_item`.

In these notes, the number of items of a particular title/instance is denoted by $n$. We're considering the performance relative to $n$ because some titles, like [the journal _Nature_](https://searchworks.stanford.edu/view/3195844), have very high numbers of items for which we need to use the circ rules to do things like determine requestability.

The FOLIO HTTP API that performs this action, [`GET /circulation/rules/request-policy`](https://s3.amazonaws.com/foliodocs/api/mod-circulation/p/circulation-rules.html#circulation_rules_request_policy_get), requires specifying four properties of the item: `item_type_id`, `loan_type_id`, `patron_type_id`, and `location_id`. We do not restrict requests by patron type, so we only concern ourselves with the other three parameters. This means that the performance impact of using this API to render a single view page in searchworks is given by:
```math
O(m), 1 \leq m \leq n
```
...where $m$ is the number of unique combinations of item type/loan type/location. The worst case is a title where every item has a _different_ loan type/location/item type ($m = n$), and the best case is a title where all items have the _same_ loan type, item type, and location ($m = 1$). In practice, however, a single HTTP request to FOLIO might be unacceptably slow for our users (or [time out](https://issues.folio.org/browse/CIRC-1783)), so even $O(1)$ performance is suspect.

We've instead opted to request all of the circ rules as plain text using the [`GET /circulation/rules`](https://s3.amazonaws.com/foliodocs/api/mod-circulation/p/circulation-rules.html#circulation_rules_get) API, save them to a file, and commit the file to version control as part of SearchWorks. We can do this because circ rules are expected to change infrequently, and we expect to be able to mediate the change process via conversations with LibSys.

Circulation rules in FOLIO's format can have multiple criteria, each of which specifies a particular set of item types, loan types, patron types, or locations to match. Criteria are combined using an `OR`, so a rule specifying multiple item types would apply to an item with any of those types. Rules [can also be nested](https://github.com/folio-org/mod-circulation/blob/master/doc/circulationrules.md#criteria) in order to combine them using `AND`: a rule with item type criteria nested underneath a rule with location criteria would affect items with any of the specified types if they are in any of the specified locations.

Our parser and transform create a flat array of `Rule` objects representing this structure. Continuing the previous example, the nested rule with item types would have been transformed into a `Rule` including both the item type criteria and the location criteria from its parents. `Rule`s also remember their indentation value and line number from the original text file. Because specificity of rules controls their priority, our list of `Rule`s is **already sorted in priority order**. This means that the first rule that applies to an item is the rule to use.

The naive implementation for finding the best rule to use would be to iterate through the full list of `Rule`s until one is found that matches the property of the item. The performance impact of using this implementation to render a single view page in searchworks is given by:
```math
O(cm), 1 \leq m \leq n, c \approx 400
```
...in the worst case, where $c$ is the total number of circ rules. This represents checking every rule for every unique item type/location/loan type combination. In practice, this might still be faster than the FOLIO HTTP API implementation, because API calls are slow.

What we would like is an implementation whose performance impact when rendering a view page in searchworks would be:
```math
```

**Comment by thatbudakguy** [comment]
blocked on #3149.

**Comment by thatbudakguy** [comment]
this is a good place to test parity; if production shows a location-level link/item-level link/no link, folio-dev should do the same.

**Comment by cbeer** [comment]
> we're currently filtering by current location to remove location-level links if the current location doesn't allow paging... is this appropriately captured in the FOLIO circ rules?

Maybe, but the way the circ rules are currently written, it seems like they're overly restrictive (e.g. nothing out of ART, including the locked stacks, is considered pageable?)

**Comment by cbeer** [comment]
> we're filtering out e.g. SEE-OTHER locations. is this appropriately captured in the FOLIO circ rules?

SEE-OTHER is now e.g. "SAL3 shelved elsewhere", and I see nothing that would exclude those (loan type is "can circulate", sometimes they have items, etc). I wonder if the circ rules need adjusting.

**Comment by cbeer** [comment]
> does FOLIO give us anything to determine mediated or aeon pageability?

No, and in fact anything in e.g. SPEC-COLL is marked as "no requests allowed".

**Comment by cbeer** [comment]
> Hopkins has some weird business logic that suppresses location-level pages if the item is available online or available from some other library. Presumably FOLIO can't do the latter, at least?

Correct, and nothing in HOPKINS is marked as pageable.

**Comment by cbeer** [comment]
> does item status factor in at all?

No, but maybe it should (e.g. for on-order/in process/ etc)

**Comment by cbeer** [comment]
>  validate whether the non-requestable locations or item on reserve logic is captured by FOLIO circ rules

Reserves loan types are marked no requests allowed. 

Other non-requestable locations are:
    - CDL
    - SEE-OTHER
    - TECH-DESK

**Comment by thatbudakguy** [comment]
> > does FOLIO give us anything to determine mediated or aeon pageability?
> 
> No, and in fact anything in e.g. SPEC-COLL is marked as "no requests allowed".

See https://github.com/sul-dlss/sul-requests/issues/1505 for a proposal to use location details to handle this.

**Comment by thatbudakguy** [comment]
> > does item status factor in at all?
> 
> No, but maybe it should (e.g. for on-order/in process/ etc)

Circ rules don't take account of this and we know we need it for item-level request links, so we're stuck maintaining some business logic around it in SearchWorks.

**Comment by thatbudakguy** [comment]
blocked by https://github.com/sul-dlss/sul-requests/issues/1505

**Comment by jcoyne** [comment]
Related to #3202
