### ISSUE TITLE
BS4 branch: "Refine your results" font size

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/SearchWorks#3562]
Both are `<h2>` elements, but in BS4 the text does not look much like a heading.

production
<img width="414" alt="Screen Shot 2023-09-28 at 9 41 49 AM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/cad52e23-bfb4-44c8-8e5f-26034fa83609">

BS4/staging
<img width="410" alt="Screen Shot 2023-09-28 at 9 42 05 AM" src="https://github.com/sul-dlss/SearchWorks/assets/1328900/2e9468c2-2919-4025-8e78-fe09bceb1530">

**Comment by jcoyne** [comment]
@cbeer this size is a Blacklight default https://github.com/projectblacklight/blacklight/blob/51d4f59385549e2031fafa616a1d5a039771bd57/app/assets/stylesheets/blacklight/_facets.scss#L99. Although we can override this, I'm wondering if we should make it configurable, or move the `.h4` into the component rather than the scss.
