### ISSUE TITLE
Restore "Appears in" context for virtual objects

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/SearchWorks#3854]
When an item is part of a virtual object, SearchWorks used to show a link to the record for the whole virtual object under the heading "Appears in" within the context widget on the item page. I believe this is the original ticket for this feature: https://github.com/sul-dlss/SearchWorks/issues/1051 

At some point in the last year or two, this context link has stopped appearing.

**Example**

This map is a page from a larger atlas: https://searchworks.stanford.edu/view/sd322dt2118

In the purl page display, you can see that it has a link to the purl for the whole atlas:

> <img width="501" alt="Screenshot 2024-02-01 at 3 27 38 PM" src="https://github.com/sul-dlss/SearchWorks/assets/8975583/875402c5-0663-42b6-a649-de34ec243bf3">

In the context sidebar, there should be a link to the [SW record for the whole atlas](https://searchworks.stanford.edu/view/10448742) (not the purl page), but currently there's only a link to the collection:

> <img width="352" alt="Screenshot 2024-02-01 at 3 28 40 PM" src="https://github.com/sul-dlss/SearchWorks/assets/8975583/b946543c-e8cb-4229-985d-ee1939d24428">

**Comment by dnoneill** [comment]
I have looked into this issue and the problem is that the set field for this record has an 'a' when indexed. When [this function is searching](https://github.com/sul-dlss/SearchWorks/blob/f2bb4664e7ee0d50d5c4b01fe1df9940b80139bc/app/models/concerns/solr_set.rb#L34-L39) it is searching for an item with the id `a10448742` however the record has the id `10448742` so it can't find it. I am wondering if it makes sense to clean the record in traject indexer side or in the search side. Open to either.

```
"set":["a10448742"],
        "set_with_title":["a10448742-|-The Cyclers' Guide and Road Book of California Containing Map of California in relief with principal Roads, Seven Sectional Maps showing all available Roads for Cyclers from Chico to San Diego, and a Map of Golden Gate Park. 1896. Price, One Dollar. Compiled and Published by Geo. W. Blum, 330 Pine St., S.F. Edward Denny  Co., Agents. (on verso) Copyrighted 1895 By Geo. W. Blum, San Francisco, Cal"],
```
