### ISSUE TITLE
Check SEE-OTHER like behavior is no longer needed in SearchWorks/indexing

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/SearchWorks#4037]
Resulting from review of https://github.com/sul-dlss/SearchWorks/pull/3990

Questions to review:
a) What are analyzed serials and how are they represented in FOLIO data?
Analyzed serials appear similar to bound-withs because separate records have relationships with each other, but metadata folks point out that these two constructs are different.
b) Will we need SEE-OTHER to handle analyzed serials? (In which case, we don't want to remove SEE-OTHER)
c) Even if we don't use SEE-OTHER as a code, will we need similar behavior in other places?

Folio to Symphony code mapping (in SW-FOLIO migration info, maybe SW traject indexer as well): Review what used to map to SEE-OTHER and see which of those may not be displaying correctly in SearchWorks anymore.

See example: https://searchworks.stanford.edu/view/53602

**Comment by jcoyne** [comment]
53602 has a child record https://searchworks.stanford.edu/view/396229. Which uses the regular Folio boundWith structure.

```
   "boundWith": {
                "item": {
                  "id": "efd8fb32-7ba4-53aa-85f5-c426992c69f1",
                  "hrid": "ai53602_1_1",
                  "status": "Available",
                  "barcode": "36105027410229"
                },
```

**Comment by jcoyne** [comment]
#2182 was where 'SEE-OTHER' was added to fix #2100

It fixed this https://searchworks.stanford.edu/?search_field=search&q=Science+fiction+adventures which is still clearly working, because `item_display_struct` has non-suppressed items.

![Image](https://github.com/sul-dlss/SearchWorks/assets/92044/6dd0def1-7cb2-4457-b2f7-ea1629dae944)

**Comment by corylown** [comment]
I think we can re-open https://github.com/sul-dlss/SearchWorks/pull/3990 and I'd be comfortable reviewing and merging the changes proposed there.

Here's the long explanation why, by answering the questions in the description:

a. What are analyzed serials and how are they represented in FOLIO data? Analyzed serials appear similar to bound-withs because separate records have relationships with each other, but metadata folks point out that these two constructs are different.

From Jeanette:
> It is easier to think of bound with and analyzed as two separate things.
> Something can be partially or fully analyzed which means any items that are analyzed get separate catalog records for the title of that particular piece. Then if there happens to be multiple items bound together we create the bound withs between them. For example if we have v. 16-17 of a serial and both are analyzed then v. 16 and v. 17 would have their own records and then v. 16 would have the barcode and be the parent and v. 17 would be the child.

**Important to note: in FOLIO the bound with relationships are the same for all items whether or not they are part of an analyzed serial.**

Yes, analyzed serials and bound-withs are different constructs, BUT I think our confusion on this point relates to the fact that some but not all analyzed serials have bound-with relationships. The bound-with relationships on analyzed serials are managed in the same way as the bound-with relationships on other records. We do not have to handle them differently. Furthermore, analyzed serials that are not bound with other items will have their own items and display just like any other item and there should be a note to the effect of "Individual vols. of this title also cataloged separately." Here's an example: https://searchworks.stanford.edu/?search_field=search&q=id%3A5460408

b) Will we need SEE-OTHER to handle analyzed serials? (In which case, we don't want to remove SEE-OTHER)

No. We do not need to handle SEE-OTHER (or *-SEE-OTHER) locations for analyzed serials. They will either be constructed like other bound-with records or have their own items.

c) Even if we don't use SEE-OTHER as a code, will we need similar behavior in other places?

I'm not sure exactly what this question means, but as far as I can tell we are already correctly handling bound-withs and analyzed serials and analyzed serials that have bound-with relationships.

**Comment by jcoyne** [comment]
@corylown I reopened and rebased #3990
