### ISSUE TITLE
Library name cut off & hours squished in "At the library" on Chrome

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/SearchWorks#4095]
Using Chrome and in the "At the Library" panel, we're seeing: 

1.  the library name get cut off if the screen window is narrow. 
2. the hours is at the very bottom of the box. It could benefit from some tweaking. 

<img width="277" alt="image" src="https://github.com/sul-dlss/SearchWorks/assets/14897546/47e41faa-3808-4664-b5e4-ae5261fcef3e">

You can see this when viewing any item record in "Earth Sciences (Branner)" library, including this one: https://searchworks.stanford.edu/view/14197139

**Comment by saseestone** [comment]
@dbranchini indicated she suggested some ways to move the hours up.

**Comment by jcoyne** [comment]
The old system looked/worked like this:

<img width="322" alt="Screenshot 2024-03-06 at 3 25 13 PM" src="https://github.com/sul-dlss/SearchWorks/assets/92044/1b7a2014-4818-459d-b750-ed3dff226835">
<img width="244" alt="Screenshot 2024-03-06 at 3 24 58 PM" src="https://github.com/sul-dlss/SearchWorks/assets/92044/35ab9b66-279f-4df8-ba7b-6dfcf486a2e7">

**Comment by jcoyne** [comment]
I'm able to restore the old behavior, but I'm not sure that is a lot better for users.  Should we make the font smaller too?  We could hide the image to make more space too.

**Comment by dbranchini** [comment]
@jcoyne , the ellipsis is probably better than a hard cutoff, but ideally, it should wrap. What about trying `overflow-wrap: break-word`? https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap.

**Comment by dbranchini** [comment]
Also, is the 3px padding under the heading necessary? Maybe try reducing it a little to 1 or 2 px? I think that's what causing the hours to but up against the edge of the header?

**Comment by jcoyne** [comment]
@dbranchini if we wrap, that completely pushed the hours out of the header.  If we make the header taller, then the square image won't span the whole height.
<img width="323" alt="Screenshot 2024-03-06 at 3 42 43 PM" src="https://github.com/sul-dlss/SearchWorks/assets/92044/c775d185-3980-4e9a-ac8e-194fe84317df">

**Comment by dbranchini** [comment]
Let's do the ellipsis for now, but I'd like to find a better solution so it can wrap. Maybe hiding the image or reducing the font size when it wraps?

**Comment by jcoyne** [comment]
@dbranchini another idea is to give this column more than 1/3 of the page when the window is narrower.

**Comment by dbranchini** [comment]
I like that idea, but it's also a problem for a longer library name, such as the Hoover Institution Library & Archives, at full screen on my laptop. I'm a little worried about changing Bootstrap columns without a lot of testing, but I tried 5 instead of 4 with the description column getting 7 instead of 6 and it still cutoff the Archive of Recorded Scound at a viewport width of 972px - so the medium breakpoint. I also tried 6 and 6 columns and that seemed to work better. Could we try changing the font-size to 16px (ish, I know you're using rem, so maybe that's 1 rem depending on the base) and adjusting the columns a for the medium breakpoint. 

Screenshots follow:

**Hoover full-width on my laptop:**
<img width="392" alt="Screenshot 2024-03-07 at 9 29 09 AM" src="https://github.com/sul-dlss/SearchWorks/assets/6816624/9baf8b58-0cfb-4d23-9970-2328499b70e3">

**Hoover reduced font-size:**
<img width="401" alt="Screenshot 2024-03-07 at 9 28 57 AM" src="https://github.com/sul-dlss/SearchWorks/assets/6816624/0aef1c52-2ae3-47e2-b908-a4cfaf9af40e">

**Archive of Recorded Sound - 972px viewport, 5/7 columns**
<img width="600" src="https://github.com/sul-dlss/SearchWorks/assets/6816624/213a6716-be25-427b-80a4-576ba0720571">

**Archive of Recorded Sound - 972px viewport, 6/6 columns**
<img width="600" src="https://github.com/sul-dlss/SearchWorks/assets/6816624/72aef79b-b689-4db6-aa35-239fc4b9e041">
