### ISSUE TITLE
Strange browser-specific cover-display behaviour

### ISSUE THREAD

**Issue by jvine** [sul-dlss/SearchWorks#720]
This record:
http://searchworks-new.stanford.edu/view/2018222

In Firefox, it shows the wrong cover.
![screen shot 2014-08-13 at 12 53 32 pm](https://cloud.githubusercontent.com/assets/6945691/3911675/adeb4766-2323-11e4-9c7c-8d2fca6bbb98.png)

In Chrome, it shows the wrong cover briefly, then updates it with the correct cover.
![wrong-cover](https://cloud.githubusercontent.com/assets/6945691/3912643/32b27d12-232d-11e4-8919-f2766480749d.gif)

**Comment by jvine** [comment]
Related to #963

**Comment by jvine** [comment]
Damn. The animated replacement isn't happening anymore, but there are still different covers shown for this record in Chrome vs. Firefox. 
http://searchworks.stanford.edu/view/2018222

**Comment by jvine** [comment]
See also #1138

**Comment by cbeer** [comment]
It looks like the Google API response includes entries for both covers (one matching on the OCLC, one matching the LCCN?):

https://books.google.com/books?jscmd=viewapi&bibkeys=,OCLC692202,LCCNa%20%2043000592&callback=jQuery111101567740049213171_1453771367540&_=1453771367541

Hashes are not ordered in javascript, and I don't see any explicit heuristics for picking which entry to use.  Is there any guidance for how we should try to pick them, especially since the API seems to not give us a way to match the bibkeys we sent with particular entry? It seems like the best we could do is something like "prefer bibkeys that contain OCLC over bare numbers", but who knows what else that might break..

**Comment by jkeck** [comment]
I think we do know that (and it is the order that we send it in).  Maybe we can match up the identifiers returned in the response with the first one we send-in (using something that can be ordered in javascript like an array) and match it up like that?

**Comment by cbeer** [comment]
We can certainly try, but, for example, in this case, we're sending `LCCNa  43000592` and getting back a response with the key `43000592`. If we're going to try to match them, it seems like we'll have to look at some more cover responses and hope they're consistent..

**Comment by jvine** [comment]
Order of preference of matches, according to gryphon-search:

1. OCLC, 2. LCCN, 3.ISBN
